service: whatsapPostMessage
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  stage: test
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 15 # optional, in seconds, default is 6
region: us-east-1
functions:
  TwilioIncommingMessage:
    handler: Personal-Interfaces/Functions/handlerIncommingMessage.handler
    name: TwilioIncommingMessage-lambda-${opt:stage}
    environment: 
      NODE_ENV: ${opt:stage}
      MONGO_PORT: 27017
      MONGO_HOST: ${file(./config/${opt:stage}.json):MONGO_HOST}
      MONGO_SECRET: ${file(./config/${opt:stage}.json):MONGO_SECRET}
      MONGO_DATABASE: ${file(./config/${opt:stage}.json):MONGO_DATABASE}
      MONGO_SET: ${file(./config/${opt:stage}.json):MONGO_SET}
      MONGO_USER: ${file(./config/${opt:stage}.json):MONGO_USER}
      BODY_REQUEST: ${file(./config/${opt:stage}.json):BODY_REQUEST}
      MONGO_SSL: true
  GetPrepayments:
    handler: Personal-Interfaces/Functions/PrePayments.get
    name: PrepaymentsRepo-get-${opt:stage}
    environment: 
      NODE_ENV: ${opt:stage}
      MONGO_PORT: 27017
      MONGO_HOST: ${file(./config/${opt:stage}.json):MONGO_HOST}
      MONGO_SECRET: ${file(./config/${opt:stage}.json):MONGO_SECRET}
      MONGO_DATABASE: ${file(./config/${opt:stage}.json):MONGO_DATABASE}
      MONGO_SET: ${file(./config/${opt:stage}.json):MONGO_SET}
      MONGO_USER: ${file(./config/${opt:stage}.json):MONGO_USER}
      BODY_REQUEST: ${file(./config/${opt:stage}.json):BODY_REQUEST}
      MONGO_SSL: true
    events: 
      - http: 
          path: /default/prepayments
          method: GET
          cors: 
            - enabled: true
            - origin: '*'
            - headers:  'Access-Control-Allow-Origin'
          name: PersonalAPI
  GetStats:
    handler: Personal-Interfaces/Functions/boxflow.get
    name: StatsRepo-get-${opt:stage}
    environment: 
      NODE_ENV: ${opt:stage}
      MONGO_PORT: 27017
      MONGO_HOST: ${file(./config/${opt:stage}.json):MONGO_HOST}
      MONGO_SECRET: ${file(./config/${opt:stage}.json):MONGO_SECRET}
      MONGO_DATABASE: ${file(./config/${opt:stage}.json):MONGO_DATABASE}
      MONGO_SET: ${file(./config/${opt:stage}.json):MONGO_SET}
      MONGO_USER: ${file(./config/${opt:stage}.json):MONGO_USER}
      BODY_REQUEST: ${file(./config/${opt:stage}.json):BODY_REQUEST}
      MONGO_SSL: true
    events: 
      - http: 
          path: /default/boxflow/stats
          method: GET
          cors: 
            - enabled: true
            - origin: '*'
            - headers:  'Access-Control-Allow-Origin'
          name: PersonalAPI
  PutPrepayments:
    handler: Personal-Interfaces/Functions/PrePayments.put
    name: PrepaymentsRepo-put-${opt:stage}
    environment: 
      NODE_ENV: ${opt:stage}
      MONGO_PORT: 27017
      MONGO_HOST: ${file(./config/${opt:stage}.json):MONGO_HOST}
      MONGO_SECRET: ${file(./config/${opt:stage}.json):MONGO_SECRET}
      MONGO_DATABASE: ${file(./config/${opt:stage}.json):MONGO_DATABASE}
      MONGO_SET: ${file(./config/${opt:stage}.json):MONGO_SET}
      MONGO_USER: ${file(./config/${opt:stage}.json):MONGO_USER}
      BODY_REQUEST: ${file(./config/${opt:stage}.json):BODY_REQUEST}
      MONGO_SSL: true
    events: 
      - http: 
          path: /default/prepayments
          method: PUT
          cors: 
            - enabled: true
            - origin: '*'
            - headers:  'Access-Control-Allow-Origin: *'
          name: PersonalAPI
  EmailChecker:
    handler: AutomationServices/AutoMailChecker/checker.start
    name: AutomationServices-EmailChecker-${opt:stage}
    events: 
      - schedule: 
        name: 'cw-start-email-checker'
        description: 'Function to connecto to Gmail :D'
        rate: rate(20 minutes)
        enabled: true
    environment: 
      MONGO_HOST: ${file(./config/${opt:stage}.json):MONGO_HOST}
      MONGO_PORT: '27017'
      MONGO_SECRET: ${file(./config/${opt:stage}.json):MONGO_SECRET}
      MONGO_SET: ${file(./config/${opt:stage}.json):MONGO_SET}
      MONGO_SSL: true
      MONGO_USER: ${file(./config/${opt:stage}.json):MONGO_USER}
      SUBJECT_SEARCHED: 'Servicio de Alertas y Notificaciones Bancolombia'
      BODY_BASE_SEARCHED: 'Bancolombia le informa'
      BODY_SKIPPED_PHRASE: 'Bancolombia le informa que su factura inscrita'
      EMAIL_USERNAME: ${file(./config/${opt:stage}.json):EMAIL_USERNAME}
      EMAIL_PASSWORD: ${file(./config/${opt:stage}.json):EMAIL_PASSWORD}
      NODE_ENV: ${opt:stage}
    