service: whatsapPostMessage
provider:
  name: aws
  runtime: nodejs12.x
  stage: test
region: us-east-1
functions:
  TwilioIncommingMessage:
    handler: POST-whatsapp/Functions/handlerIncommingMessage.handler
    name: TwilioIncommingMessage-lambda-${opt:stage}
    package: 
      - POST-whatsapp/*
    environment: 
      NODE_ENV: ${opt:stage}
      MONGO_PORT: 27017
      MONGO_HOST: ${file(./config/${opt:stage}.json):MONGO_HOST}
      MONGO_SECRET: ${file(./config/${opt:stage}.json):MONGO_SECRET}
      MONGO_SET: ${file(./config/${opt:stage}.json):MONGO_SET}
      MONGO_USER: ${file(./config/${opt:stage}.json):MONGO_USER}
      MONGO_SSL: true
    events: 
      - httpApi: 
        method: POST
        name: PersonalAPI
        path: /default/whatsapp